### PR TITLE
Add a setup.py

### PR DESCRIPTION
**Pull request by brandonwillard**
Simply adds a `setup.py` with an `entry_point` for the Jupyter CLI.

### CODE REVIEW

**Comment by gilch** [comment]
The setup should include the requirements.txt. Hebigo does, of course, have a dependency on `hissp`, and now `jupyter-console` as well. `hypothesis` is only used for the tests, so maybe shouldn't be included. Maybe we should split the requirements.txt into two files.

**Comment by brandonwillard** [comment]
I split the test dependency into a `requirements-dev.txt` and made `setup.py` read from that and `requirements.txt`.

**Comment by gilch** [comment]
`tests_require` is deprecated as is everything related to the setuptools `test` command.

I tried building and installing the package (from this branch), and it's not working right. I get
```
FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
```
during install. After reading up a bit, I think this approach is backwards.

Instead, the install dependencies should all be in the `setup.py`, and a single `requirements.txt` should get them from there and then have the other dependencies for dev/testing, like
```
--editable .
hypothesis
```
Apparently, you can have arbitrary `pip install` options in the requirements file. TIL.

I'm also not sure if we have to do something special to `setup.py` for the `src/` layout.

I'm also worried about having the `__name__ == '__main__'` thing in a file named `__main__`. Wouldn't that always run regardless?

**Comment by brandonwillard** [comment]
> `tests_require` is deprecated as is everything related to the setuptools `test` command.

Removed.

> I tried building and installing the package (from this branch), and it's not working right. I get
> 
> ```
> FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
> ```
> 
> during install.

Are you using `pip install` or something else?


> After reading up a bit, I think this approach is backwards.
> 
> Instead, the install dependencies should all be in the `setup.py`, and a single `requirements.txt` should get them from there and then have the other dependencies for dev/testing, like
> 
> ```
> --editable .
> hypothesis
> ```
> 
> Apparently, you can have arbitrary `pip install` options in the requirements file. TIL.

To clarify, you're talking about putting the install requirements in `setup.py` and duplicating them in the `requirements.txt`&mdash;alongside any distinct dev/testing requirements?


> I'm also not sure if we have to do something special to `setup.py` for the `src/` layout.

I haven't run into any problems with the layout under `pip install`.

> I'm also worried about having the `__name__ == '__main__'` thing in a file named `__main__`. Wouldn't that always run regardless?

No, I don't think that condition is necessary; plus, I just tried without it, and it still seems to work.

**Comment by gilch** [comment]
I want to be able to test that the hebigo package built with this PR's setup.py properly installs and functions in a fresh Python 3.8 virtual environment before merging. So far, I haven't been able to make it work. This might have revealed a preexisting problem unrelated to this PR, but we'd still need to fix it before I can test this one properly.

> Are you using `pip install`

Yes.

> To clarify, you're talking about putting the install requirements in `setup.py` and duplicating them in the `requirements.txt`&mdash;alongside any distinct dev/testing requirements?

I am not. By the DRY principle we should prefer that "Every piece of knowledge must have a single, unambiguous, authoritative representation within a system." This is not a prohibition of duplication *per se*, but where duplication cannot be avoided, then one instance should be authoritative, and any others should be automatically generated from that one.

Our initial approach was to make the `requirements.txt` the authoritative representation, and the `setup.py` read from that. (I think Hy also did it that way.) I'm saying that's backwards. The `setup.py` should be the authoritative representation of the *install requirements* and the `requirements.txt` should read from that one (via `-e`). But the `requirements.txt` will add to that any *development requirements* not required for a normal install.

**Comment by brandonwillard** [comment]
> I want to be able to test that the hebigo package built with this PR's setup.py properly installs and functions in a fresh Python 3.8 virtual environment before merging. So far, I haven't been able to make it work. This might have revealed a preexisting problem unrelated to this PR, but we'd still need to fix it before I can test this one properly.

We can set up CI and test it out.  That would at least have us looking at the exact same situation.



> No. By the DRY principle we should prefer that "Every piece of knowledge must have a single, unambiguous, authoritative representation within a system." This is not a prohibition of duplication _per se_, but where duplication cannot be avoided, then one instance should be authoritative, and any others should be automatically generated from that one.

Yeah, I really didn't think that duplication was the desired approach, but I see what you're going for now.  One second, I'll update it to reflect that.

**Pull request merged**
